config/routes.rb
Hospitalview::Application.routes.draw do
  resources :hospitals
  resources :charts, :only => [:index]
  root :to => 'hospitals#index'

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
	def index
		@hospitals = Hospital.select("state, hospital_type, count(hospital_type) as total_hospitals").group("hospital_type","state").order("state")

    	respond_to do |format|
    	  format.html # index.html.erb
    	  format.json { render json: @hospitals }
    	end
    end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  require 'will_paginate/array'
  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all.paginate(:page => params[:page], :per_page => 50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hospitals }
    end
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
    @hospital = Hospital.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hospital }
    end
  end

  # GET /hospitals/new
  # GET /hospitals/new.json
  def new
    @hospital = Hospital.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hospital }
    end
  end

  # GET /hospitals/1/edit
  def edit
    @hospital = Hospital.find(params[:id])
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(params[:hospital])

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to @hospital, notice: 'Hospital was successfully created.' }
        format.json { render json: @hospital, status: :created, location: @hospital }
      else
        format.html { render action: "new" }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hospitals/1
  # PUT /hospitals/1.json
  def update
    @hospital = Hospital.find(params[:id])

    respond_to do |format|
      if @hospital.update_attributes(params[:hospital])
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital = Hospital.find(params[:id])
    @hospital.destroy

    respond_to do |format|
      format.html { redirect_to hospitals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/charts/index.html.erb
<h1>Hospitals by Type</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>State</th>
      <th># Hopsitals</th>
      <th>Hopsital Type</th>
    </tr>
  </thead>
  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.state %></td>
        <td><%= hospital.total_hospitals %></td>
        <td><%= hospital.hospital_type %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hospitals/_form.html.erb
<%= form_for @hospital, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Hospital</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :address, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :city, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :city, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :state, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :state, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :zip, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :zip, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :county, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :county, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :hospital_type, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :hospital_type, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :owner, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :owner, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :emergency_services, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :emergency_services, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :location, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :location, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', hospitals_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/hospitals/edit.html.erb
<%= render :partial => 'form' %>

app/views/hospitals/index.html.erb
<h1>Hospitals</h1>
<%= will_paginate @hospitals %> 

<table class="table table-striped">
  <thead>
    <tr>
      <th>Hospital Name</th>
      <th>City</th>
      <th>County</th>
      <th>State</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= link_to hospital.name, hospital_path(hospital) %></td>
        <td><%= hospital.city %></td>
        <td><%= hospital.county %></td>
        <td><%= hospital.state %></td>
        <td>
          <%= link_to 'Edit', edit_hospital_path(hospital), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', hospital_path(hospital), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @hospitals %> 

app/views/hospitals/new.html.erb
<%= render :partial => 'form' %>

app/views/hospitals/show.html.erb
<h1>Hospital</h1>

<table class="table table-striped">

<tr>
  <td><b>Name</b></td>
  <td><%= @hospital.name %></td>
</tr>

<tr>
  <td><b>Address</b></td>
  <td><%= @hospital.address %></td>
</tr>

<tr>
  <td><b>City</b></td>
  <td><%= @hospital.city %></td>
</tr>

<tr>
  <td><b>State</b></td>
  <td><%= @hospital.state %></td>
</tr>

<tr>
  <td><b>Zip</b></td>
  <td><%= @hospital.zip %></td>
</tr>

<tr>
  <td><b>County</b></td>
  <td><%= @hospital.county %></td>
</tr>

<tr>
  <td><b>Type</b></td>
  <td><%= @hospital.hospital_type %></td>
</tr>

<tr>
  <td><b>Owner</b></td>
  <td><%= @hospital.owner %></td>
</tr>

<tr>
  <td><b>Emergency services</b></td>
  <td><%= @hospital.emergency_services %></td>
</tr>

<tr>
  <td><b>Location</b></td>
  <td><%= @hospital.location %></td>
</tr>
</table>

<div class="form-actions">
  <%= link_to 'Back', hospitals_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_hospital_path(@hospital), :class => 'btn' %>
  <%= link_to 'Delete', hospital_path(@hospital), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospitalview</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Hospital View</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Hospitals", hospitals_path %></li>
          <li><%= link_to "Charts", charts_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">

<%= yield %>
</div>
</body>
</html>